# Generated by Django 4.2.30 on 2026-10-06 06:05

from datetime import timedelta

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_order_tracking(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    OrderStatusEvent = apps.get_model('store', 'OrderStatusEvent')
    progression = [
        'order_placed',
        'payment_confirmed',
        'order_confirmed',
        'processing',
        'packed',
        'shipped',
        'out_for_delivery',
        'delivered',
    ]
    legacy_statuses = {'pending': 'order_placed', 'confirmed': 'payment_confirmed'}

    for order in Order.objects.all().iterator():
        order.order_status = legacy_statuses.get(order.order_status, order.order_status)
        if not order.estimated_delivery:
            order.estimated_delivery = order.timestamp.date() + timedelta(days=5)
        if order.order_status in {'shipped', 'out_for_delivery', 'delivered'}:
            order.tracking_number = order.tracking_number or f'SC{order.pk:09d}'
            order.shipped_at = order.shipped_at or order.timestamp
        order.save(update_fields=[
            'order_status',
            'estimated_delivery',
            'tracking_number',
            'shipped_at',
        ])

        if order.order_status in progression:
            statuses = progression[:progression.index(order.order_status) + 1]
        else:
            statuses = ['order_placed', order.order_status]
        for status_value in statuses:
            OrderStatusEvent.objects.get_or_create(
                order_id=order.pk,
                status=status_value,
                defaults={'timestamp': order.timestamp},
            )


def reverse_order_tracking_backfill(apps, schema_editor):
    Order = apps.get_model('store', 'Order')
    Order.objects.filter(order_status='order_placed').update(order_status='pending')
    Order.objects.filter(order_status='payment_confirmed').update(order_status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_name',
            field=models.CharField(blank=True, default='SmartCart Express', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('payment_confirmed', 'Payment Confirmed'), ('order_confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], default='order_placed', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('payment_confirmed', 'Payment Confirmed'), ('order_confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order')),
            ],
            options={
                'db_table': 'store_order_status_event',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.RunPython(backfill_order_tracking, reverse_order_tracking_backfill),
    ]
