# Generated by Django 4.2.30 on 2026-10-06 06:22

from django.db import migrations, models


def normalize_legacy_payment_methods(apps, schema_editor):
    Payment = apps.get_model('store', 'Payment')
    Payment.objects.filter(payment_method__in=['stripe', 'mock', 'card']).update(payment_method='online')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_carrier_name_order_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_payment_methods, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online', 'Online Payment'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card')], default='online', max_length=20),
        ),
    ]
