from django.urls import path
from .views import (
    AdminDashboardView,
    AdminOrderListView,
    AdminProductView,
    AdminReportExportView,
    AdminUserListView,
    CartItemCreateView,
    CartItemUpdateDeleteView,
    CartView,
    CategoryListView,
    LoginUserView,
    MeView,
    NotificationListView,
    NotificationReadView,
    OrderDetailView,
    OrderListCreateView,
    PaymentConfirmView,
    PaymentCreateView,
    ProductDetailView,
    ProductListView,
    RegisterUserView,
)

urlpatterns = [
    path('auth/register', RegisterUserView.as_view(), name='register-user'),
    path('auth/login', LoginUserView.as_view(), name='login-user'),
    path('auth/me', MeView.as_view(), name='me-user'),
    path('categories', CategoryListView.as_view(), name='categories'),
    path('products', ProductListView.as_view(), name='products'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product-detail'),
    path('cart', CartView.as_view(), name='cart'),
    path('cart/items', CartItemCreateView.as_view(), name='cart-item-create'),
    path('cart/items/<int:pk>', CartItemUpdateDeleteView.as_view(), name='cart-item-update-delete'),
    path('orders', OrderListCreateView.as_view(), name='orders'),
    path('orders/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('payments/create', PaymentCreateView.as_view(), name='payment-create'),
    path('payments/confirm', PaymentConfirmView.as_view(), name='payment-confirm'),
    path('notifications', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:pk>/read', NotificationReadView.as_view(), name='notification-read'),
    path('admin/users', AdminUserListView.as_view(), name='admin-users'),
    path('admin/products', AdminProductView.as_view(), name='admin-products'),
    path('admin/orders', AdminOrderListView.as_view(), name='admin-orders'),
    path('admin/dashboard', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/reports', AdminReportExportView.as_view(), name='admin-report-export'),
]
